# NVIDIA Device Plugin
#
# TODO: Add NVIDIA device plugin manifests:
# kubectl kustomize https://github.com/NVIDIA/k8s-device-plugin \
#   > infrastructure/base/nvidia-device-plugin/manifest.yaml
#
# Or reference directly:
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.17.0/deployments/static/nvidia-device-plugin.yml
