apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Deploy in order
  - ../../base/cert-manager
  - ../../base/tailscale-operator
  # - ../../base/oci-ccm  # Uncomment when configured
  # - ../../base/nvidia-device-plugin  # Uncomment when configured
  
  # Encrypted secrets
  - tailscale-secret.enc.yaml
